# Filename: .github/workflows/azure-app-service.yml
# Description: A GitHub Actions workflow to build and deploy the full-stack Scholargy application to Azure App Service.

name: Build and Deploy Scholargy to Azure App Service

# Trigger: This workflow runs on every push to the 'main' branch.
on:
  push:
    branches:
      - main  # Updated to match your current branch
      - master  # Also trigger on master for compatibility
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'  # Use Node.js 22 LTS as requested
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # --- Install Dependencies ---
    - name: Install dependencies
      run: npm install

    # --- Frontend Build Steps ---
    - name: Build frontend
      run: CI=false npm run build
      working-directory: frontend

    # Step 3: Package the application for deployment
    - name: Package application for Azure
      run: |
        rm -rf deploy
        mkdir -p deploy/public

        # Copy backend source files (excluding package.json)
        cp -r backend/* deploy/
        rm -f deploy/package.json deploy/package-lock.json  # Remove backend package files

        # Copy frontend build into public folder
        cp -r frontend/build/* deploy/public/

        # Copy root-level config files (with dependencies) - THIS IS THE ONLY package.json
        cp package*.json deploy/
        cp startup.js deploy/
        cp web.config deploy/
        cp .deployment deploy/

        echo "Deployment package contents:"
        ls -la deploy/
        echo "📁 Root package.json (with all dependencies):"
        cat deploy/package.json | grep -A 10 '"dependencies"'
        echo "📁 Verifying express is in dependencies:"
        grep -i express deploy/package.json
        echo "📁 Public directory (frontend build):"
        ls -la deploy/public/

    # Step 4: Deploy to Azure App Service
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'scholargy-dz3lcl3szkm74'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy 