# Filename: .github/workflows/azure-app-service.yml
# Description: A GitHub Actions workflow to build and deploy the full-stack Scholargy application to Azure App Service.

# 1. Name of the workflow
name: Build and Deploy Scholargy to Azure App Service

# 2. Trigger: This workflow runs on every push to the 'main' branch.
on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# 3. Jobs: Defines the sequence of tasks to run.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a Linux runner provided by GitHub

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    # Use a specific version of Node.js for consistency.
    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: lts/* # Use a Long-Term Support (LTS) version
        cache: 'npm'

    # --- Frontend Build Steps ---
    - name: Frontend - Install dependencies
      run: npm install
      working-directory: ./frontend # Run this command in the frontend folder

    - name: Frontend - Build application
      run: npm run build
      working-directory: ./frontend # Run this command in the frontend folder

    # --- Backend Preparation Steps ---
    - name: Backend - Install dependencies
      run: npm install
      working-directory: ./backend # Run this command in the backend folder

    # Step 3: Package the application for deployment
    # This step copies the built frontend into the backend, creating a single deployable unit.
    - name: Package application
      run: cp -r frontend/build backend/build

    # Step 4: Deploy to Azure App Service
    # This action uses your publish profile secret to securely log in and deploy the code.
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scholargy-dz3lcl3szkm74' # The name of your Azure App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # The secret you created in GitHub
        package: ./backend # Deploy the entire backend folder
